university = [
    {"name": "Boğaziçi Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 1000, "score": 480},
    {"name": "Orta Doğu Teknik Üniversitesi", "location": "Ankara", "department": "Bilgisayar Mühendisliği", "ranking": 2000, "score": 470},
    {"name": "İstanbul Teknik Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 3000, "score": 460},
    {"name": "Sabancı Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 3500, "score": 455},
    {"name": "Koç Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 4000, "score": 450},
    {"name": "İstanbul Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 5000, "score": 440},
    {"name": "Hacettepe Üniversitesi", "location": "Ankara", "department": "Bilgisayar Mühendisliği", "ranking": 6000, "score": 430},
    {"name": "Marmara Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 7000, "score": 420},
    {"name": "Ankara Üniversitesi", "location": "Ankara", "department": "Bilgisayar Mühendisliği", "ranking": 8000, "score": 410},
    {"name": "Bozok Üniversitesi", "location": "Yozgat", "department": "Bilgisayar Mühendisliği", "ranking": 12000, "score": 400},
    {"name": "Ege Üniversitesi", "location": "İzmir", "department": "Bilgisayar Mühendisliği", "ranking": 13000, "score": 395},
    {"name": "Gazi Üniversitesi", "location": "Ankara", "department": "Bilgisayar Mühendisliği", "ranking": 14000, "score": 390},
    {"name": "Selçuk Üniversitesi", "location": "Konya", "department": "Bilgisayar Mühendisliği", "ranking": 15000, "score": 380},
    {"name": "Çukurova Üniversitesi", "location": "Adana", "department": "Bilgisayar Mühendisliği", "ranking": 16000, "score": 375},
    {"name": "Dumlupınar Üniversitesi", "location": "Kütahya", "department": "Bilgisayar Mühendisliği", "ranking": 17000, "score": 370},
    {"name": "İzmir Yüksek Teknoloji Enstitüsü", "location": "İzmir", "department": "Bilgisayar Mühendisliği", "ranking": 18000, "score": 365},
    {"name": "Trakya Üniversitesi", "location": "Edirne", "department": "Bilgisayar Mühendisliği", "ranking": 19000, "score": 360},
    {"name": "Atatürk Üniversitesi", "location": "Erzurum", "department": "Bilgisayar Mühendisliği", "ranking": 20000, "score": 350},
    {"name": "İnönü Üniversitesi", "location": "Malatya", "department": "Bilgisayar Mühendisliği", "ranking": 21000, "score": 340},
    {"name": "Karadeniz Teknik Üniversitesi", "location": "Trabzon", "department": "Bilgisayar Mühendisliği", "ranking": 22000, "score": 330},
    {"name": "Kocaeli Üniversitesi", "location": "Kocaeli", "department": "Bilgisayar Mühendisliği", "ranking": 23000, "score": 320},
    {"name": "Yıldız Teknik Üniversitesi", "location": "İstanbul", "department": "Bilgisayar Mühendisliği", "ranking": 24000, "score": 310},
    {"name": "Afyon Kocatepe Üniversitesi", "location": "Afyon", "department": "Bilgisayar Mühendisliği", "ranking": 25000, "score": 300},
    {"name": "Mersin Üniversitesi", "location": "Mersin", "department": "Bilgisayar Mühendisliği", "ranking": 26000, "score": 290},
    {"name": "Ondokuz Mayıs Üniversitesi", "location": "Samsun", "department": "Bilgisayar Mühendisliği", "ranking": 27000, "score": 280},
    {"name": "Akdeniz Üniversitesi", "location": "Antalya", "department": "Bilgisayar Mühendisliği", "ranking": 28000, "score": 270},
    {"name": "Sakarya Üniversitesi", "location": "Sakarya", "department": "Bilgisayar Mühendisliği", "ranking": 29000, "score": 260},
    {"name": "Giresun Üniversitesi", "location": "Giresun", "department": "Bilgisayar Mühendisliği", "ranking": 30000, "score": 250},
    {"name": "Nevşehir Hacı Bektaş Veli Üniversitesi", "location": "Nevşehir", "department": "Bilgisayar Mühendisliği", "ranking": 31000, "score": 240},
    {"name": "Mustafa Kemal Üniversitesi", "location": "Hatay", "department": "Bilgisayar Mühendisliği", "ranking": 32000, "score": 230},
    {"name": "Zonguldak Karaelmas Üniversitesi", "location": "Zonguldak", "department": "Bilgisayar Mühendisliği", "ranking": 33000, "score": 220},
    {"name": "Kastamonu Üniversitesi", "location": "Kastamonu", "department": "Bilgisayar Mühendisliği", "ranking": 34000, "score": 210},
    {"name": "Batman Üniversitesi", "location": "Batman", "department": "Bilgisayar Mühendisliği", "ranking": 35000, "score": 200},
    {"name": "Bingöl Üniversitesi", "location": "Bingöl", "department": "Bilgisayar Mühendisliği", "ranking": 36000, "score": 190},
    {"name": "Siirt Üniversitesi", "location": "Siirt", "department": "Bilgisayar Mühendisliği", "ranking": 37000, "score": 180},
    {"name": "Şırnak Üniversitesi", "location": "Şırnak", "department": "Bilgisayar Mühendisliği", "ranking": 38000, "score": 170},
    {"name": "Kırıkkale Üniversitesi", "location": "Kırıkkale", "department": "Bilgisayar Mühendisliği", "ranking": 39000, "score": 160},
    {"name": "Aksaray Üniversitesi", "location": "Aksaray", "department": "Bilgisayar Mühendisliği", "ranking": 40000, "score": 150}
]
